---
# This file will be overwritten when the site is generated

exclude: [README.md]
collections:
  areas:
    output: true

# Site specific data
country: Wales
country_id: 2
list_owner_screen_name: political_wales
submission_url: http://localhost:5000/applications/2/submissions
